# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Angular App

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '20.x'

      - name: npm install
        shell: bash
        run: 'npm install'

      - name: npm build prod
        shell: bash
        run: 'npm run build-prod'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3.1.3
        with:
          name: app
          path: dist/browser

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'my-site'
          slot-name: 'Production'
          publish-profile: ${{ secrets.GH_TOKEN }}
          package: .
